{% set version = "2.9.3" %}

package:
  name: allennlp-models
  version: {{ version }}

source:
  url: https://github.com/allenai/allennlp-models/archive/v{{ version }}.tar.gz
  sha256: a1304180d4a25a77958eb6747dfbc210cb2edac59b854dac89f4034a2a77780e

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win or py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - sysroot_linux-64 ==2.17   # [linux64]
  host:
    - python
    - pip
  run:
    - python
    - allennlp =={{ version }}
    - conllu ==4.4.1
    - datasets
    - ftfy
    - nltk >=3.6.5
    - py-rouge ==1.1
    - pytorch >=1.7,<1.11
    - word2number >=1.1
  run_constrained:
    # failing test suite with 0.9.0; can be dropped once allennlp has this as its lower bound;
    # torchvision 0.10.0 needs pytorch 1.9, but the resolver gets lost in the weeds somewhere and
    # adds an old pytorch-cpu, see https://github.com/conda-forge/pytorch-cpu-feedstock/issues/65
    - torchvision >=0.10.0
    - pytorch-cpu >=1.9     # [osx]

test:
  requires:
    - pytest
    - flaky
    - spacy-model-en_core_web_sm
  source_files:
    - tests/
    - test_fixtures/
  imports:
    - allennlp_models
  commands:
    # from upstream: https://github.com/allenai/allennlp-models/blob/main/Makefile
    - pytest --color=yes -rf -m "not pretrained_model_test and not pretrained_config_test"

about:
  home: https://github.com/allenai/allennlp-models
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Officially supported AllenNLP models

  doc_url: https://docs.allennlp.org/models/stable/
  dev_url: https://github.com/allenai/allennlp-models

extra:
  recipe-maintainers:
    - h-vetinari
