{% set version = "2.5.0" %}

package:
  name: allennlp-models
  version: {{ version }}

source:
  url: https://github.com/allenai/allennlp-models/archive/v{{ version }}.tar.gz
  sha256: 56696c3c983273be060e0351a14a20a628c7da48c39acd12acf12da06f2c95c6

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  skip: true  # [win]

requirements:
  build:
    - sysroot_linux-64 ==2.17   # [linux64]
  host:
    - python
    - pip
  run:
    - python
    - allennlp =={{ version }}
    - conllu ==4.4
    - ftfy
    - nltk
    - py-rouge ==1.1
    - pytorch >=1.7,<1.9
    - word2number >=1.1

test:
  requires:
    - pytest
    - flaky
    - spacy-model-en_core_web_sm
  source_files:
    - tests/
    - test_fixtures/
  imports:
    - allennlp_models
  commands:
    # from upstream: https://github.com/allenai/allennlp-models/blob/main/Makefile
    - pytest --color=yes -rf -m "not pretrained_model_test and not pretrained_config_test"

about:
  home: https://github.com/allenai/allennlp-models
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Officially supported AllenNLP models

  doc_url: https://docs.allennlp.org/models/stable/
  dev_url: https://github.com/allenai/allennlp-models

extra:
  recipe-maintainers:
    - h-vetinari
